// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbgvgmydgdhelihcipqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZ3ZnbXlkZ2RoZWxpaGNpcHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNTI0NDQsImV4cCI6MjA3NjgyODQ0NH0._musY9jJNqHJutr5JNhkAMZM1sFBYLVNj5E1xwP_1b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});